name: Go Docker Image CI

on:
  push:
    branches: [ main ]


jobs:

  build:

    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: del
      DOCKER_REPOSITORY: vultik
      TAG_PREFIX: dev
      ARGOCD_ENDPOINT: argocd.vultik.com #without https
      INSECURE: true
      APP_NAME: golang
      
    steps:

    - uses: actions/checkout@v3

    - name: Docker Login
      uses: docker/login-action@v1.14.1
      with:
        #registry:
        username: vultik
        password: ${{ secrets.DOCKER_PASSWORD }}
        ecr: auto
        logout: true

    - name: Build the Docker image
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        docker build --file Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$TAG_PREFIX-$git_hash .
    - name: Docker Push
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "Pushing image to Docker Hub..."
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$TAG_PREFIX-$git_hash
        echo "::set-output name=image::$DOCKER_REPOSITORY/$IMAGE_NAME:$TAG_PREFIX-$git_hash"
    - name: Get Image Tag
      id: getImageTag
      run: |
        git_hash=$(git rev-parse --short "$GITHUB_SHA")
        echo "::set-output name=imagetag::$TAG_PREFIX-$git_hash"
#    - name: ArgoCD Application Sync Action
#      uses: omegion/argocd-actions@v0.2.0
#      with:
#        address: ${{ env.ARGOCD_ENDPOINT }}
#        token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
#        insecure: ${{ env.INSECURE }}
#        appName: ${{ env.APP_NAME }}
#        action: sync
#        imageTag: ${{steps.getImageTag.outputs.imagetag}}
    - name: Sync ArgoCD Application
      uses: butterfly1924/argocd-actions@master
      with:
        address: ${{ env.ARGOCD_ENDPOINT }}
        token: ${{ secrets.ARGOCD_AUTH_TOKEN }}
        insecure: ${{ env.INSECURE }}
        appName: ${{ env.APP_NAME }}
        imageTag: ${{steps.getImageTag.outputs.imagetag}}
